services:
  web:
    image: nginx
    ports:
      - 127.0.0.1:8080:80
    working_dir: /app
    volumes:
      - ./templates:/usr/share/nginx/html

  db:
    image: postgres:latest
    environment:
        - ${POSTGRES_DB}
        - ${POSTGRES_USER}
        - ${POSTGRES_PASSWORD}
    ports:
      - 127.0.0.1:8082:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data